### ISSUE TITLE
ACE/TAO and RTnet wiki page with Xenomai 2.6.4 and Ubuntu 14.04

### ISSUE THREAD

**Issue by cfpperche2** [kuka-isir/rtt_lwr#1]
Do you have any plans to create a wiki for rtnet build and install with this architecture ?

also a wiki about how to install ace/tao (for OROCOS CORBA dataflow) with this architecture will be very useful, since the official documentation is very deprecated.

best regards

thanks!

**Comment by ahoarau** [comment]
First draft can be found here : https://github.com/kuka-isir/rtt_lwr/wiki/RTnet-setup

No idea though about ace/TAO, I'm using OmniORB : 

```
sudo apt-get install omniorb-idl omniorb omniorb-nameserver
```

Then compile orocos with omniorb/corba options : 

```
catkin_make_isolated --install -DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB
```

**Comment by cfpperche2** [comment]
Ok, omniorb also fit to me 

Very nice explanation about RTnet.

Do you have an example about how to integrate Orocos and RTnet to transfer data between Orocos components ?

My doubt is
Is it possible send RT UDP/TCP packages between periodic rt activities ?

Thanks!!!!

**Comment by ahoarau** [comment]
> Do you have an example about how to integrate Orocos and RTnet to transfer data between Orocos components ?

In rtt_lwr, it is only used in the [lwr_fri component](https://github.com/ahoarau/lwr_hardware/blob/indigo-devel/lwr_fri/src/FRIComponent.cpp#L487) and the [ati sensor component](https://github.com/kuka-isir/ati_sensor/blob/master/src/ft_sensor.cpp#L169). It works exactly as a [standard C socket](http://www.linuxhowtos.org/C_C++/socket.htm). You can use it to talk between hard RT periodic components but you'll have to define your way to convert your data to be sent/received.

So yes, it is possible. But do you need it to talk between two deployers ? remote computer ? Otherwise, orocos ports should be used.

**Comment by cfpperche2** [comment]
Yes, in my project (autonomous vehicle) I have 6 "modules" (computers in network) and 1 supervisor (another computer) that controls a state machine in these modules with a reactive activity.

The supervisor also have to send to these modules a timestamp message (called heartbeat) periodically in order to detect possible failures in these modules
(supervisor expect receive a response message when heartbeat has arrive in these modules). 

These activities must be hard real time.

I thought make this communication (reactive and periodic) with rtnet, what you think ?

Best regards

**Comment by ahoarau** [comment]
Ok you can have a "master" computer that triggers all the updateHooks of the other 6 using RTnet.
The master is a periodic activity, the other have to be aperiodic to be triggered when new data comes.
look at the [lwr_fri component](https://github.com/ahoarau/lwr_hardware/blob/indigo-devel/lwr_fri/src/FRIComponent.cpp#L487). It's a slave to the robot's new data : period is 0, and the update hook is : 

``` c++
void updateHook(){
    rt_recv(master_server); // This waits on new data
    // Processing, write to ports etc
    this->trigger(); // Triggers the next updatehook() (i.e run as fast as you can)
}
```

**Comment by cfpperche2** [comment]
It's looks like I was thinking, 

I have another doubt, RTnet enable automatically the synchronization from master to slave clocks? Or I have to do this manually ? 

If manually, I do it in rtnet config file? 

thanks for all

**Comment by ahoarau** [comment]
Again, RTnet is just a set of (realtime capable) drivers and does not know about Orocos. Orocos doesn't know about RTnet either. It's just a way to send data via ethernet in a realtime environment.
If the master Orocos sends data at constant rate, and the others are aperiodic waiting for new master's data, then you'll have some sort of synchronization, even though the internal Orocos clocks won't be synced at all.

For ROS, you'll need the (system) clocks synced or you won't be able to use tf for example. Use NTP (set one PC as ntp server, the other ones as listeners) to solve this problem.
