### ISSUE TITLE
Ruby Issues with Ubuntu 18.04

### ISSUE THREAD

**Issue by lnnx2006** [kuka-isir/rtt_lwr#13]
> Errors     << metaruby:cmake /home/fei/isir/orocos-2.9_ws/logs/metaruby/build.cmake.000.log                               
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find Ruby (missing: RUBY_INCLUDE_DIR RUBY_LIBRARY) (found version
>   "1.8.0")
> 

When catkin build with Ubuntu 18.04, the above problems will be encounted. Could anybody update the packages ?

**Comment by ahoarau** [comment]
I'm surprise rosdep did not install the lua dev libs.
Did you follow the instructions from http://rtt-lwr.readthedocs.io/en/latest/install/install-16.04-kinetic.html
You can try : 
`sudo apt install liblua5.1-0-dev`

I have no experience on 18.04 yet. Other packages might also be missing.

**Comment by lnnx2006** [comment]
I think it is related with the following issue : [](url) https://github.com/ros/rosdistro/pull/18302
Actually, the lua dev libs are all installed. I don't need to use 
`sudo apt install liblua5.1-0-dev`

Thanks a lot as well!

**Comment by ahoarau** [comment]
So.. is it solved ? What was the fix exactly ?

**Comment by lnnx2006** [comment]
Not yet! I tried to modified rosdep for ruby libs as indicated by the above link. The problem is remaining the same. Hope this will be solved by 

I also tried to build my code using Ubuntu 18.04. Since the gazebo version is at least 9. Many APIs are changed. So it still needs to fix several problems.

**Comment by JimmyDaSilva** [comment]
@lnnx2006 Did you succeeded in installing everything on Ubuntu 18.04 ?

**Comment by ahoarau** [comment]
In the end the "lua" part of orocos is absolutely optional, and not even used in `rtt_lwr`.

**Comment by JimmyDaSilva** [comment]
The following PR solved the issue:
https://github.com/orocos-toolchain/utilrb/pull/42
