### ISSUE TITLE
RTnet-config.cmake

### ISSUE THREAD

**Issue by cfpperche2** [kuka-isir/rtt_lwr#2]
Hi, when I do "catkin_make"  in my workspace, I get an warning like 

I'm using a "fork" of [ati_sensor/cmake/Modules/](https://github.com/kuka-isir/ati_sensor/tree/master/cmake/Modules)
and my CMakeLists.txt is based on [RTnet-setup wiki](https://github.com/kuka-isir/rtt_lwr/wiki/RTnet-setup)

CMake Warning at vilma-framework/vilma_core/CMakeLists.txt:35 (find_package):
  By not providing "FindRTnet.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "RTnet", but
  CMake did not find one.

  Could not find a package configuration file provided by "RTnet" with any of
  the following names:

```
RTnetConfig.cmake
rtnet-config.cmake
```

  Add the installation prefix of "RTnet" to CMAKE_PREFIX_PATH or set
  "RTnet_DIR" to a directory containing one of the above files.  If "RTnet"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Using RTnet

How to fix it ?

Thanks

**Comment by ahoarau** [comment]
Maybe you forgot to add the path where CMake can find the _Findxxx.cmake_ : 

``` bash
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
```

Where ${CMAKE_SOURCE_DIR}/cmake is where you put the FindRTnet.cmake file.

**Comment by cfpperche2** [comment]
thanks, solved 
..
list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake/modules)
..
