### ISSUE TITLE
Pc breaks when compiling 

### ISSUE THREAD

**Issue by AntonisKats** [kuka-isir/rtt_lwr#23]
I am following the tutorial of this project in a Ubuntu 18.04 PC. When i try to compile it, my PC stops responding. When I restart it, i can't open the terminal. In the tutorial, it says that a powerful PC is required. What are required features of a PC in order to use this software? Do you think that the problem isn't my PC's performance?

**Comment by ahoarau** [comment]
Hello, if you compile and it freezes, it's probably out of ram. try to compile with `catkin build -j1`. It's gonna take a very long time but works. Default settings uses all the cpus and compiling can take up to 16Gb of RAM ...

**Comment by AntonisKats** [comment]
Thank you very much. It works fine now.
