### ISSUE TITLE
Error when performing a "Make" with Xenomai 

### ISSUE THREAD

**Issue by JH51224** [kuka-isir/rtt_lwr#25]
Hi there, I am currently having issue while trying to make orocos-toolchain 2.9 run with xenomai 3.0.5 kernel. I am getting the error where, it sends me : XENOMAI_INCLUDE , XENOMAI_LIB , XENOMAI_POSIX_INCLUDE_DIR, XENOMAI_POSIX_LIBRARY and XENOMAI_NATIVE_LIB could not be found. However I have xenomai located within my usr folder. Although I know where to find Posix Library, Posix include dir, lib and include. I am unsure if I am to put the native include folder or should i just link the /usr/xenomai/lib to the XENOMAI_NATIVE_LIB. 
I have tried placing /usr/xenomai/lib into XENOMAI_NATIVE_LIB,however, when I compile it, it complains that it is unable to find native/task.h. 

This is the error I got after I placed in the XENOMAI_INCLUDE = /usr/xenomai/include , XENOMAI_LIB = /usr/xenomai/lib  and XENOMAI_NATIVE_LIB=/usr/xenomai/lib
```

[  0%] Building CXX object rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/Activity.cpp.o
In file included from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/base/../os/fosi.h:51:0,
                 from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/base/../os/ThreadInterface.hpp:42,
                 from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/base/ActivityInterface.hpp:42,
                 from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/base/RunnableInterface.hpp:41,
                 from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/Activity.hpp:43,
                 from /home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/Activity.cpp:44:
/home/hrg/isir/orocos-2.9_ws/src/orocos_toolchain/rtt/rtt/base/../os/xenomai/fosi.h:76:10: fatal error: native/task.h: No such file or directory
 #include <native/task.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/build.make:62: recipe for target 'rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/Activity.cpp.o' failed
make[2]: *** [rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/Activity.cpp.o] Error 1
CMakeFiles/Makefile2:377: recipe for target 'rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/all' failed
make[1]: *** [rtt/CMakeFiles/orocos-rtt-xenomai_dynamic.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2


```
Will appreciate all the help I can get! I am trying to use xenomai and orocos for a project in university!

**Comment by ahoarau** [comment]
Hello, it's because the master branch of rtt does not have this PR yet : https://github.com/orocos-toolchain/rtt/pull/301
Try this !

**Comment by JH51224** [comment]
Thank you so much! I succeeded in compiling orocos!
