### ISSUE TITLE
RTnet UDP with timeout

### ISSUE THREAD

**Issue by cfpperche2** [kuka-isir/rtt_lwr#3]
Hi, please help me,

Are there any way to create the rtnet_udp recvfrom with a timeout ?

thanks

**Comment by ahoarau** [comment]
``` c++
nanosecs_rel_t timeout = (long long)timeval_.tv_sec*1E9 + (long long)timeval_.tv_usec*1E3;
rt_dev_ioctl(socketHandle_, RTNET_RTIOC_TIMEOUT, &timeout)
```

 https://github.com/kuka-isir/ati_sensor/blob/master/src/ft_sensor.cpp#L126
