### ISSUE TITLE
non blocking recvfrom

### ISSUE THREAD

**Issue by cfpperche2** [kuka-isir/rtt_lwr#4]
Hi Antoine, how are you ?

How can I make a call to the recvfrom function with RTnet and do not block my orocos component?

Which is the correct way?

thanks

**Comment by ahoarau** [comment]
Could you explain more what component does what ? :)

**Comment by cfpperche2** [comment]
Sorry, I did a shit...

I was invoking an exception when the timeout was exceeded in my recvfrom function and thus the component was taken to errorHook and cleanupHook, breaking my application

I managed to solve.

Thanks for support me
